# Generated by Django 4.0.4 on 2022-06-03 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='regions',
            new_name='region',
        ),
    ]
