# Generated by Django 4.0.4 on 2022-06-01 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'abilities',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('pokemon_number', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'areas',
            },
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'moves',
            },
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('flavor_text', models.CharField(max_length=400)),
                ('capture_rate', models.FloatField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
            ],
            options={
                'db_table': 'pokemons',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'regions',
            },
        ),
        migrations.CreateModel(
            name='Sprite',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('front_default', models.CharField(max_length=300)),
                ('back_default', models.CharField(max_length=300, null=True)),
                ('back_shiny', models.CharField(max_length=300, null=True)),
                ('back_shiny_female', models.CharField(max_length=300, null=True)),
                ('back_female', models.CharField(max_length=300, null=True)),
                ('front_shiny', models.CharField(max_length=300, null=True)),
                ('front_shiny_female', models.CharField(max_length=300, null=True)),
                ('front_female', models.CharField(max_length=300, null=True)),
            ],
            options={
                'db_table': 'sprites',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'types',
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nick_name', models.CharField(max_length=200)),
                ('party_member', models.BooleanField()),
                ('id_pokemons', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pokemon.pokemon')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('value', models.BigIntegerField()),
                ('pokemon_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pokemon.pokemon')),
            ],
            options={
                'db_table': 'stats',
            },
        ),
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pokemon_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pokemon.pokemon')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pokemon.type')),
            ],
            options={
                'db_table': 'pokemons_types',
            },
        ),
        migrations.CreateModel(
            name='PokemonMove',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('move_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pokemon.move')),
                ('pokemon_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pokemon.pokemon')),
            ],
            options={
                'db_table': 'pokemons_moves',
            },
        ),
        migrations.CreateModel(
            name='PokemonArea',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pokemon.area')),
                ('pokemon_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pokemon.pokemon')),
            ],
            options={
                'db_table': 'pokemons_areas',
            },
        ),
        migrations.CreateModel(
            name='PokemonAbility',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ability_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pokemon.ability')),
                ('pokemon_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pokemon.pokemon')),
            ],
            options={
                'db_table': 'pokemons_abilities',
            },
        ),
        migrations.AddField(
            model_name='pokemon',
            name='id_sprites',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pokemon.sprite'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('id_regions', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pokemon.region')),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.AddField(
            model_name='area',
            name='id_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pokemon.location'),
        ),
    ]
