# Generated by Django 4.0.4 on 2022-06-02 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'abilities',
            },
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'db_table': 'moves',
            },
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('flavor_text', models.CharField(max_length=400)),
                ('capture_rate', models.FloatField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('color', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'pokemons',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sprite',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('front_default', models.CharField(max_length=300, null=True)),
                ('back_default', models.CharField(max_length=300, null=True)),
                ('back_shiny', models.CharField(max_length=300, null=True)),
                ('back_shiny_female', models.CharField(max_length=300, null=True)),
                ('back_female', models.CharField(max_length=300, null=True)),
                ('front_shiny', models.CharField(max_length=300, null=True)),
                ('front_shiny_female', models.CharField(max_length=300, null=True)),
                ('front_female', models.CharField(max_length=300, null=True)),
            ],
            options={
                'db_table': 'sprites',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'db_table': 'types',
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nick_name', models.CharField(max_length=200)),
                ('is_party_member', models.BooleanField()),
                ('specie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pokemon.pokemon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'storages',
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('value', models.BigIntegerField()),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stats', to='pokemon.pokemon')),
            ],
            options={
                'db_table': 'stats',
            },
        ),
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='types', to='pokemon.pokemon')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pokemon.type')),
            ],
            options={
                'db_table': 'pokemons_types',
            },
        ),
        migrations.CreateModel(
            name='PokemonMove',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pokemon.move')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='moves', to='pokemon.pokemon')),
            ],
            options={
                'db_table': 'pokemons_moves',
            },
        ),
        migrations.CreateModel(
            name='PokemonArea',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pokemons', to='places.area')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pokemon.pokemon')),
            ],
            options={
                'db_table': 'pokemons_areas',
            },
        ),
        migrations.CreateModel(
            name='PokemonAbility',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pokemon.ability')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='abilities', to='pokemon.pokemon')),
            ],
            options={
                'db_table': 'pokemons_abilities',
            },
        ),
        migrations.AddField(
            model_name='pokemon',
            name='sprite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pokemon.sprite'),
        ),
    ]
