# Generated by Django 4.0.4 on 2022-06-01 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='storage',
            table='storages',
        ),
    ]
