# Generated by Django 4.0.4 on 2022-06-01 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_alter_storage_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='id_sprites',
            new_name='sprite_id',
        ),
        migrations.RenameField(
            model_name='storage',
            old_name='id_pokemons',
            new_name='pokemon_id',
        ),
    ]
