# Generated by Django 4.0.4 on 2022-06-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_rename_id_sprites_pokemon_sprite_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
