# Generated by Django 4.0.4 on 2022-06-01 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_alter_region_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='id_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='id_regions',
            new_name='regions',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='sprite_id',
            new_name='sprite',
        ),
        migrations.RenameField(
            model_name='pokemonability',
            old_name='ability_id',
            new_name='ability',
        ),
        migrations.RenameField(
            model_name='pokemonability',
            old_name='pokemon_id',
            new_name='pokemon',
        ),
        migrations.RenameField(
            model_name='pokemonarea',
            old_name='area_id',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='pokemonarea',
            old_name='pokemon_id',
            new_name='pokemon',
        ),
        migrations.RenameField(
            model_name='pokemonmove',
            old_name='move_id',
            new_name='move',
        ),
        migrations.RenameField(
            model_name='pokemonmove',
            old_name='pokemon_id',
            new_name='pokemon',
        ),
        migrations.RenameField(
            model_name='pokemontype',
            old_name='pokemon_id',
            new_name='pokemon',
        ),
        migrations.RenameField(
            model_name='pokemontype',
            old_name='type_id',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='stat',
            old_name='pokemon_id',
            new_name='pokemon',
        ),
        migrations.RenameField(
            model_name='storage',
            old_name='pokemon_id',
            new_name='pokemon',
        ),
        migrations.RenameField(
            model_name='storage',
            old_name='user_id',
            new_name='user',
        ),
    ]
