# Generated by Django 4.0.4 on 2022-06-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0005_rename_id_location_area_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
