# Generated by Django 4.0.4 on 2022-06-01 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0007_alter_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='area',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.DO_NOTHING, to='pokemon.area'),
            preserve_default=False,
        ),
    ]
