# Generated by Django 4.0.4 on 2022-06-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0008_pokemon_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='color',
            field=models.CharField(default='green', max_length=100),
            preserve_default=False,
        ),
    ]
