# Generated by Django 4.0.4 on 2022-06-01 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0010_alter_sprite_front_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='area',
        ),
    ]
