# Generated by Django 4.0.4 on 2022-06-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0011_remove_pokemon_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
