# Generated by Django 4.0.4 on 2022-06-02 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0012_alter_area_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemon',
            options={'managed': True},
        ),
    ]
