# Generated by Django 4.0.4 on 2022-06-02 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0013_alter_pokemon_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='pokemon_number',
            new_name='pokemon_count',
        ),
        migrations.AlterField(
            model_name='area',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='areas', to='pokemon.location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='regions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='locations', to='pokemon.region'),
        ),
        migrations.AlterField(
            model_name='pokemonability',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='abilities', to='pokemon.pokemon'),
        ),
        migrations.AlterField(
            model_name='pokemonarea',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pokemons', to='pokemon.area'),
        ),
        migrations.AlterField(
            model_name='pokemonmove',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='moves', to='pokemon.pokemon'),
        ),
        migrations.AlterField(
            model_name='pokemontype',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='types', to='pokemon.pokemon'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stats', to='pokemon.pokemon'),
        ),
    ]
